### ISSUE TITLE
Set default target for pull requests

### ISSUE THREAD

**Issue by mjhouse** [themotte/rDrama#10]
Default target for pull requests is the original Aevann1/rDrama repo, and should be changed to this fork ([this](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch) may be relevant).

**Comment by zorbathut** [comment]
It looks like this lets you change the fork label but not the repo; by being a fork of their repo, we're stuck forever pull-requesting to them. Thankfully, it also sounds like Github support is able to disconnect this easily (to the point where there's a bot that does half of it for you); I've sent them a support request and will update when there's news.

**Comment by zorbathut** [comment]
(that was a mis-mention, ignore it)

**Comment by mjhouse** [comment]
> It looks like this lets you change the fork label but not the repo; by being a fork of their repo, we're stuck forever pull-requesting to them. Thankfully, it also sounds like Github support is able to disconnect this easily (to the point where there's a bot that does half of it for you); I've sent them a support request and will update when there's news.

Alright, that's cool. The forever-tied-to-rDrama thing is aggravating.

**Comment by zorbathut** [comment]
Done!
