### ISSUE TITLE
Should we have publically visible upvote/downvote records?

### ISSUE THREAD

**Issue by mjhouse** [themotte/rDrama#101]
I reworked the userpage a bit, and it looks like the Simps/Haters links are leading to scoreboard-style pages of other users that have upvoted you. I'm not sure how this affects motivations or if it's something we want to keep. For now, I changed the simpls/haters labels to upvoters/downvoters but left the links and endpoints in. 

This issue is to discuss whether we need this at all.

**Comment by zorbathut** [comment]
I'm pretty sure this is a bad idea for us, I don't want that info public. There's a lot of value in anonymous feedback.

I've been thinking of adding some kind of Discord-esque emoji-reply support, and I think public records of that *is* useful - it's basically a way of doing a zero-effort comment reply without needing to actually make the reply - but it also won't have much impact besides "a reply".

**Comment by mjhouse** [comment]
I think there was a discussion on LessWrong a few months ago about doing something similar. I'm tentatively on board with that. If no one else has any objections, we can make an issue for removing the upvoters/downvoters endpoints and the links from profile pages and wherever else they are.

**Comment by zorbathut** [comment]
I am tentatively thinking that this should be left admin-only; it might be occasionally a useful tool to deal with abuse.

**Comment by mjhouse** [comment]
I agree with that. I've made an issue for this, so I'm going to close the discussion. If anyone objects or has something to add, you can reopen and comment.
