### ISSUE TITLE
Formatting of the markdown preview doesn't display html entities correctly

### ISSUE THREAD

**Issue by mjhouse** [themotte/rDrama#105]
TwoLargeSnakesMating via discord:

> the comment preview HTML entities being rendered literally: root cause is the marked.js changes in 309bf44f1. we ported that into upstream in 80b792967 and reverted in f0dbe7168 because we had the same issue. I didn't dig much into debugging it because the XSS attack surface which motivated the change looked fairly limited—we do sanitize (admittedly not all that well) before storing.

Image taken from @JulianRota's comment on #102: 

![image](https://user-images.githubusercontent.com/4141157/172057159-6a005998-3624-46bd-bb5d-49d5367de47d.png)

**Comment by JulianRota** [comment]
That cited commit looks like it has a ton of custom JS, which makes me a little suspicious. There's gotta be some NPM library somewhere that does this correctly that we could either pull in or copy the code out of.

**Comment by mjhouse** [comment]
Yeah, I'm looking at the latest marked.js release. I'll stick it into my local build and see if that resolves it.

**Comment by mjhouse** [comment]
It looks like just dropping the latest marked.js build into the project and using it without any custom stuff resolves this issue:
![image](https://user-images.githubusercontent.com/4141157/172058249-e7b7499e-c6b3-4d34-92f9-0ca6a1d55165.png)
![image](https://user-images.githubusercontent.com/4141157/172058313-3dbe61ab-78e7-487d-b1e7-d236c36c471c.png)

**Comment by mjhouse** [comment]
Initial changes are on branch [fix_unrendered_html_entities](https://github.com/themotte/rDrama/tree/fix_unrendered_html_entities)

**Comment by mjhouse** [comment]
@faul-sname Hey, so it looks like you initially split out the custom markdown parsing stuff into `marked.custom.js` and moved `marked.js` to the vendor directory. Later, to fix the lack of [html sanitization](https://github.com/themotte/rDrama/commit/309bf44f12ba1068dd6b96186371744ca10c57c0), you added the `tokenToHTMLElement` function and some other stuff. Did the new code in 309bf44f12ba1068dd6b96186371744ca10c57c0 do anything else besides sanitizing the preview html?

@zorbathut, if the above is correct, are you cool with using DOMPurify rather than our own hand-rolled html cleaner stuff? I think that's the lib recommended by [the marked.js guys](https://marked.js.org/#installation).

**Comment by mjhouse** [comment]
If the marked.custom.js additions were mainly for adding special spoiler syntax, I think that can be done more cleanly with an extension for marked.js. I added that in commit 03aa2ca48e5feb8f8ea8a1ba79babaf84e416971:
![spoiler_demo](https://user-images.githubusercontent.com/4141157/172070283-75522b72-875c-4b1c-980a-3cb686433b91.gif)

**Comment by mjhouse** [comment]
Resolved when #107 is merged

**Comment by mjhouse** [comment]
#107 is merged
