### ISSUE TITLE
Signout doesn't always work

### ISSUE THREAD

**Issue by mjhouse** [themotte/rDrama#110]
* On the settings page after changing an avatar, signing out will prompt the user to resend a form
* A few times I've signed out and the avatar/username is unchanged until I refresh the page (I don't remember where)

**Comment by painejohn** [comment]
:wave: Interested in having a go at this. @mjhouse Can you assign this to me as it seems I can't self assign?

**Comment by mjhouse** [comment]
The title is a little misleading- I think it *does* actually sign you out, but it fails to update the UI. I would include full steps to reproduce, but I just noticed it in passing and was in a rush, so I didn't think to figure out exactly how to do that.
