### ISSUE TITLE
Make upvoters/downvoters pages and endpoints admin-only

### ISSUE THREAD

**Issue by mjhouse** [themotte/rDrama#112]
(discussion in #101)

There are four stats/pages/metrics that we want to make admin-only:
* Upvoters
* Downvoters
* Upvoted
* Downvoted

- [x] Hide the related elements on profile pages except for admins
- [x] Make the related pages accessible only to admins
- [x] Search the project to make sure there are no other references

**Comment by JulianRota** [comment]
Fixed by #121
