### ISSUE TITLE
Add a cap on the number of mentions

### ISSUE THREAD

**Issue by mjhouse** [themotte/rDrama#115]
This issue is to discuss adding a cap to the number mentions that can be used in a single submission. This has ongoing performance implications when users spam large numbers of mentions and then other people visit the page. See #104 for details. 

I'm not sure what the priority should be or if this should even be a concern until we have a production site, but I thought that if we didn't have an issue we would probably forget.

**Comment by painejohn** [comment]
:wave: I could work on this. 

From https://github.com/themotte/rDrama/issues/104#issuecomment-1149838977, a cap of 500 seems like an ok starting point. I'll play around with this to see how the number of mentions affects the timing to see if there's a better number than 500.

**Comment by painejohn** [comment]
Some rough numbers for hitting the POST api_comment endpoint:
- 100 mentions: 0.27s
- 300 mentions: 0.73s
- 600 mentions: 1.57s

Then, for loading a post, I added 20 comments, each with 300 mentions and the GET post_id function takes 0.06s to return. From the FE side, it takes 1.87s to load the page (w/o mention avatars, so getting a bunch of 404s for them). I haven't looked at this with more granularity, but the _themotte_ container spikes to about 30% cpu usage.

This is a little fuzzy, but we could set the limit of mentions to, say, 100 and see how that holds up. Thoughts @mjhouse @zorbathut ?

**Comment by zorbathut** [comment]
Sure, that sounds reasonable. I'm having trouble thinking of a legit reason someone needs more than that anyway, and once there *is* a limit, it'll be easy to change it later if we need to.
