### ISSUE TITLE
Make downvotes be downvotes

### ISSUE THREAD

**Issue by JulianRota** [themotte/rDrama#116]
Currently, true votes are tracked in the voting tables, but for the purposes of coins/karma and thread/comment score and sorting, downvotes are counted as upvotes. I don't think this is going to work for us, we're going to need true downvotes.

* Downvotes for should subtract from a user's karma, as currently stored in `truecoins`
* Downvotes should rank threads and comment lower in the sorting order

**Comment by zorbathut** [comment]
*Note*: Is there an easy way to centralize the "true karma" calculations? If so, please do so! I may want to experiment with weird karma calculations in the future.

**Comment by JulianRota** [comment]
Fixed by #123
