### ISSUE TITLE
Improve signup email theme.

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#131]
It's really pink, and even if it wasn't, it still looks like butt.

**Comment by DinoInNameOnly** [comment]
Is this referring to the sign up page? It's no longer pink and I would not personally describe its appearance as particularly butt-like, what work is left here?

![Screen Shot 2022-11-04 at 5 07 48 PM](https://user-images.githubusercontent.com/112996131/200091538-228c01a8-4b84-41c1-868e-1ed5797ae999.png)

**Comment by zorbathut** [comment]
No, the actual email sent to you for email verification:

![image](https://user-images.githubusercontent.com/160754/200110646-ac142328-418e-4a21-adbf-b013dd3ed635.png)

(sensitive parts blacked out, obviously)

It's going to be kind of tricky to work on, you'll probably need to rig up some hack code to extract the HTML before sending so you can see what it looks like.
