### ISSUE TITLE
Implement easily-readable usernotes.

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#14]
This is a big project, be warned.

We need an equivalent to the Reddit Moderator Toolbox usernotes. This tool lets the mods easily see hand-authored notes per user, with each note associated with a comment. This is how we track who needs a longer timeout and it's honestly pretty vital.

I strongly recommend installing Reddit Moderator Toolbox, making a subreddit, getting some people to post in it (you're welcome to ping me), and just playing around with it. I can try to write up a longer detailed description here if necessary though. If a lack of description is holding you back from starting this, *please ping me* and I'll solve it.

This involves backend code and frontend code; if you're more comfortable in the backend world, feel free to hook that up with a crummy frontend and I'm sure someone will fix up the rest.

**Comment by mjhouse** [comment]
I'm going to take this issue and see what I can figure out. If I can't make any progress in a day or two, I'll un-assign myself and dump any notes about what I figure out in the comments here.

**Comment by mjhouse** [comment]
I've got the database modifications and a python model for the ORM now. So here's what would go into a frontend implementation for usernotes on TheMotte:

* Everywhere that a post or comment author's name shows up, we need a clickable label that is visible only to mods. It will either be some short default like `U` or the beginning of the latest usernote.
* Clicking on that label pops up a window that contains all notes associated with the user, each of which optionally contains a link to a referenced comment or post.

The backend database stuff is mostly roughed-in, but still needs:

* A column in the usernotes table that has [options](https://docs.sqlalchemy.org/en/14/core/type_basics.html?highlight=enum#sqlalchemy.types.Enum) for:
     * Good Contributor
     * Spam Watch
     * Spam Warning
     * Abuse Warning
     * Bana
     * Permanent Ban
     * Bot Ban
     * Others?
* Routes/code to get and create usernotes
 
@zorbathut Am I missing anything here? Is there a super list of usernotes somewhere that needs to be written as well? Do we need the Ban tags if there are not subreddits/holes?

**Comment by zorbathut** [comment]
Here, lemme adjust that tag list a bit:

* Quality
* Good
* Comment
* Warning
* Tempban
* Permban
* Spam
* Bot

We do need those tags because they function as reminders; at some point we'll be trying to detect alts and we want to be able to see a usernote to explain why the original user got banned, and I want all of these in one place. Honestly it's a little silly to have both usernotes *and* notes on bans, I'd love to reconcile these somehow, but that's a project in its own right and is not worth doing right now.

> It will either be some short default like U or the beginning of the latest usernote.

Feel free to just go with U right now. I want to play around with some better ways of displaying this, but "latest usernote" was honestly never a good solution.

> Is there a super list of usernotes somewhere that needs to be written as well?

I kind of want to import our current usernotes somehow, but that's *really difficult* because we don't even have the accounts registered yet. If you can think of a way this will be easy, go for it, but don't worry too much about it.

Other than that, looks good!
