### ISSUE TITLE
Change default profile picture and banner.

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#15]
Right now they're very, uh, Drama.

Either replace them with something better (be imaginative! don't just use another castle!), or replace them with something neutral and then I'll look at your changelist and say "oh, that's how it's done, cool". Part of this task is really "figure out how to change the default profile picture and banner" and a push is the best way to demonstrate that you've done this.

Note:

There's something in the game industry that I call "design by default", which is that if you design something, and it's good enough, it might just turn into the actual thing we use. If you think you're good enough at doing the less-codey things, just do it. If you don't, but you're cool with doing the coding work, please do the coding work and insert something blatantly wrong where the actual content is meant to go, then note it here so someone goes through and does the final prep (probably Zorba).

**Comment by mjhouse** [comment]
Related to #7 so I'm taking both.

**Comment by mjhouse** [comment]
Default profile picture was changed in #88 when I removed the emoji that was being used previously. I'll find an image and change the profile picture.
