### ISSUE TITLE
html fuzzing breaks all the things

### ISSUE THREAD

**Issue by devonandchris** [themotte/rDrama#160]
I posted the text from https://github.com/citybasebrooks/XSS-Filter-Evasion/blob/master/payloads and everything went pear-shaped. But not a pear emoji. Curious.

The preview was all messed up. It is probably vulnerable if I felt like it, although I have trouble imagining an attack scenario.

Trying to make the post gave a 500 error.

**Comment by zorbathut** [comment]
Good find! We'll take care of it.
