### ISSUE TITLE
comments dynamically added to page have wrong nesting

### ISSUE THREAD

**Issue by devonandchris** [themotte/rDrama#162]
When you reply to a comment, the page inserts your comment into the conversation, but it's nested at the same level as the parent you reply to.

Reloading fixes this.

**Comment by DinoInNameOnly** [comment]
Is this sill a problem? I just tested it locally and I don't see the behavior described, everything shows up at the correct level of nesting immediately. 

![Screen Shot 2022-09-16 at 12 08 37 AM](https://user-images.githubusercontent.com/112996131/190578040-05fc1388-c529-407a-b088-4ae4db517314.png)

**Comment by zorbathut** [comment]
I think someone already fixed this without linking it to this bug. Thanks for checking! :)
