### ISSUE TITLE
Android background color is hot pink

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#164]

**Comment by TLSM** [comment]
This one is probably(?) either:

https://github.com/themotte/rDrama/blob/defe23ea16509a14a7516fd23f061f668bf18844/files/assets/browserconfig.xml#L6

or https://github.com/themotte/rDrama/blob/defe23ea16509a14a7516fd23f061f668bf18844/files/templates/default.html#L76 https://github.com/themotte/rDrama/blob/defe23ea16509a14a7516fd23f061f668bf18844/env#L28

Though I thought Android used the Web App Manifest, which appears to correctly use `#FFFFFF` in both the repo and in prod: https://www.dev.themotte.org/assets/manifest_TheMotte.json
