### ISSUE TITLE
Creating a text post of 5000 alternating zero-width spaces and newlines causes a 500 error

### ISSUE THREAD

**Issue by AnonRoamWoe** [themotte/rDrama#167]
Specifically, if you repeat the following line in the text field until the character count reads between 9000 and 10000 and try to post, it breaks.
`
​`

If you max out the text box and use the full 20000 characters, posting fails with this text: 
![2022-08-16-18:35:18-screenshot](https://user-images.githubusercontent.com/111396154/184996953-c571a32c-1a35-4209-8a2e-693101a9aad5.png)

Similar errors occur when commenting long strings of newlines and zero-width-spaces

**Comment by zorbathut** [comment]
How on earth did you find that?

Good catch, will fix :D

**Comment by official-techsupport** [comment]
Interesting, it doesn't break the "upstream" unless I'm doing something wrong (commenting to help Zorba with locating the issue maybe and also if Snakes keeps an eye on this repo).

[test.txt](https://github.com/themotte/rDrama/files/9355110/test.txt)

**Comment by AnonRoamWoe** [comment]
Huh that's working here too. Just a sec finding something that breaks it again

**Comment by AnonRoamWoe** [comment]
Ok try this. This input is consistently causing the 500 for me

Edit: NEVERMIND, as soon as I upload it here it stops breaking. I am extremely confused.

Edit: Aaaaaand this file is breaking things again. The file hasn't changed. No less confused

[breaks.txt](https://github.com/themotte/rDrama/files/9355167/breaks.txt)

**Comment by official-techsupport** [comment]
Fascinating. Maybe it has something to do with the last newline or other weird encoding problem? What OS/browser/editor are you doing this with?

**Comment by AnonRoamWoe** [comment]
I'm on nixos 20.05 with firefox 103.0.2. Trying other browsers now to see if I can find any sort of pattern to this.

**Comment by AnonRoamWoe** [comment]
In chromium 103.0.5060.134 with a different account the file I posted above seems to cause the error some of the time. I emptied my clipboard to be sure I was correctly pasting the file contents, and pasted it in eight times with titles "a", "a", "b", "b", "c", "c", "d", and "d". The first "a", "b", "c", and "d" caused an error. The second "a", "b", "c", and "d" all succeeded.

I posted more "d"s afterwards and they seem to have succeeded, but they just redirect me to the successful "d" post and do not create a new post. I assume this is the correct behavior for repeated identical posts.

Edit: tried again in firefox - "e": fail, "e": success, "f": fail, "f": fail, "f": fail, "f": fail, "g": fail, "g": fail
other than the success in the second attempt, every attempt caused a 500 error.

Edit: copied the failed request as cURL, it is attached here
[failed-curl.txt](https://github.com/themotte/rDrama/files/9355467/failed-curl.txt)

**Comment by zorbathut** [comment]
This may be the error, which makes me suspicious that you've hit a borderline O(n^2) case. It may also be succeeding once in a while and then caching it for a while.

![image](https://user-images.githubusercontent.com/160754/185016291-36a37e38-0ef1-4cf6-a198-cdc40383a862.png)

(I know, this shouldn't be a screenshot, don't ask, it is a tale of sadness and obsolete hardware)

**Comment by official-techsupport** [comment]
@zorbathut Yes, looks like O(n^2) in a dependency of a dependency, argh. Though I didn't read the actual code, but the `reparentChildren` name is highly suggestive. I don't know if we should be very worried about it, it carries a DDoS risk but since we can switch off the sign in functionality with one click and ban all accounts that do this, it would be little more than a mild annoyance.

On a related note, you probably want to acquire this commit: https://github.com/Aevann1/rDrama/commit/548030fcf1c28 which improves the timeout mechanism to make sure that it doesn't trigger during processing of an unrelated request (if there was an exception so we did not disable the alarm). Not that it seem to be happening in this case, but self-sabotaging error handling is icky.

**Comment by DinoInNameOnly** [comment]
Is this still an issue? I just tried with the breaks.txt attached and it worked a couple of times. It creates an empty post.
![Screen Shot 2022-11-04 at 3 31 46 PM](https://user-images.githubusercontent.com/112996131/200084332-9c750a75-a748-44cf-8177-aa420edd2230.png)

**Comment by zorbathut** [comment]
We've had some changes to the parser and this may have ended up fixed in the process. Guess we'll keep an eye out for it!
