### ISSUE TITLE
Implement "filtered" for both comments and posts.

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#17]
Filtered posts are invisble to everyone except the poster, and hang out until a mod gets to approve/remove them. This is pretty important as a first line of defense against spam/trolling.

This may already exist. I actually don't know.

**Comment by mottelurk** [comment]
This doesn't appear to exist with a cursory 15 minutes of checking.

**Comment by zorbathut** [comment]
Dang, that would've been so easy :) Guess the `complicated` label was justified, then!

**Comment by JulianRota** [comment]
This exact thing doesn't exist currently. But what we do have is the post flagging system. Users can file reports on a post, which stays visible but goes in a [list for Admins to review](https://github.com/themotte/rDrama/blob/frost/files/routes/admin.py#L472). Admins can either approve or ban a post.

So the question is, do we want to try and twist the flagging system into something more like this? Or build a whole new system to enforce this rule?

Twisting the flagging system into this would look something like having a "new user" flag on users that would cause all of their posts and comments to be flagged automatically. Those would still be visible currently until an Admin actively removed them. Presumably there'd be some sort of criteria or admin UI to remove this "new user" flag. There's also a Shadowban system that might help be part of this.

Or we could build a whole new feature to do this.

**Comment by zorbathut** [comment]
The "not visible until approved" part is actually important, unfortunately.

I know comments can already be visible or removed; it may be that this is a boolean that can be converted into an enum. Once we have some kind of per-comment-and-post filtered status it's relatively easy to apply that status appropriately as users post things.

**Comment by zorbathut** [comment]
(This also gets more complicated because it has irritating consequences; like, people shouldn't get notifications when a filtered reply is made to their comment, but they *should* get a notification when it's unfiltered. I expect this to be a source of headaches, it's probably the single biggest ask in here, it's still P1, this should tell you how important it is.)
