### ISSUE TITLE
Replying to any PM causes a 500 error

### ISSUE THREAD

**Issue by AnonRoamWoe** [themotte/rDrama#170]
![2022-08-16-18:50:23-screenshot](https://user-images.githubusercontent.com/111396154/184998703-40e25bfc-986e-458d-9082-9bed21116fb3.png)

I get the same behavior in both firefox 103.0.2 and chromium 103.0.5060.134

**Comment by zorbathut** [comment]
I think it's not just "replying to your own PM", I think it's "replying to any PM". Pretty sure this is the same as #172 but I'm leaving them both around for now just in case.
