### ISSUE TITLE
Lingering rDrama gimmicks / dead code paths — remove?

### ISSUE THREAD

**Issue by TLSM** [themotte/rDrama#185]
Noticed some rDrama features that don't look to have been completely gutted. Any of these need removing?

- [ ] "Get Them Help" button on profiles. In its original implementation, this is entirely satirizing the reddit feature that sends a user suicide helpline information. Which, well, was often abused for trolling people (the implication being they ought to, ahem, **k**eep **y**ourself **s**afe).
- [ ] Fart mode. Still a toggle for it in /admin/ though looks to have been removed from the templates.
- [ ] Gambling (blackjack, slots, treasure). Since coins look to not be used anywhere, these aren't terribly important, but the code paths for all three are still there and functional in local testing. Treasure especially may be somewhat confusing, since it's still in the templates and appx. 1% of comments will get visibly rewarded with coins the user can't see the balance of elsewhere.
- [ ] Copyrighted assets. The /assets folder has: the entirety of Crab Rave, assorted anime femboy pictures, `dildo.webp`, four samples of fart sounds (`1.webp` through `4.webp`; trying to evade "adblocker beano" but they are actually mp3s), among other things.
- [ ] Special threads. The `ADMINISTRATORS` array in helpers/const.py (see #151) and a number of thread IDs (in the 37xxx range) in routes/comments.py:api_comment refers to thread IDs that don't exist in TheMotte and may be an unfortunate surprise in a few months when you get to those IDs. They were originally intended to permit non-technical users to upload site assets (sidebars, banners, badges) directly to prod. ADMINISTRATORS similarly provided special behavior for commenting in those threads.

**Comment by zorbathut** [comment]
Those all sounds like good things to pull, yeah. I don't think it's immediately desperate but we should get to them sooner rather than later.

Thanks for the list, we've sorta been running into things gradually.

**Comment by zorbathut** [comment]
I think you might have done this today :V Anything left, or should this be closed?

**Comment by TLSM** [comment]
Still need to gut the `ADMINISTRATORS` logic, which I did in that one bloated commit from a couple days I haven't PR'd yet (for want of a cleaner commit). Fair to close this though, yup.
