### ISSUE TITLE
Contact Admins (modmail) prompts for email for no good reason.

### ISSUE THREAD

**Issue by TLSM** [themotte/rDrama#186]
The /contact form has a field for email, which is solely used for display in the generated modmail notification. I _believe_ this is a holdover from when /contact was not `@auth_required` (perhaps all the way back on Ruqqus) and was usable for logged out users. However, it would take substantial refactoring to make this functionality useful—for one, the generated notification uses `author_id=v.id` and would instead need to generate a notification from a system account and then provide some mechanism to shunt replies over email, and also to receive replies therefrom. For another, logged out users bothering the admins might not be desirable.

In the upstream, we removed this field entirely for UX reasons, since users who wanted to modmail didn't understand why they had to put an email in. Relevant code sections:
https://github.com/themotte/rDrama/blob/4cfd1d5a5b8bc212c96625b5d3681ad3a79009b3/files/routes/static.py#L288-L295
https://github.com/themotte/rDrama/blob/4cfd1d5a5b8bc212c96625b5d3681ad3a79009b3/files/templates/contact.html#L26-L31

**Comment by zorbathut** [comment]
I admit I'm a little worried about us breaking the user-creation system and just kinda not noticing. I'm not totally sure what to do about that. Maybe hope that they use the social links on the side?

**Comment by TLSM** [comment]
For the upstream, we tend to fairly quickly find out when we badly broke prod via Discord. Only time that didn't work was the Cloudflare outage a ~month back, which took both the site and Discord down for an hour. (ETA: Also, we have special case logic for one of the admins to receive notifications whenever a user signs up. The rare occasions we've broken account creation, he tends to notice within a day. This is also a potential cheap solution.)

In the context of this particular issue, if you're wanting the Contact form to serve that purpose, you'll probably have to turn it into an `@auth_desired` route and have special case logic for when `v == None` to generate the notification from a system account. That alone should be pretty simple, though having any way to reply to them via the modmail interface would be a fair bit of work.

**Comment by zorbathut** [comment]
Yeah, I think I like "provide that functionality and punt on any way of replying"; we'll just handle replies out-of-band if we need to.

I'm gonna call that long-term, though; I'm putting "remove the email slot" as a P2, and setting up the whole contact-form-for-not-logged-in-people thing as a P4. If whoever gets to this wants to do both parts at once, go for it, but it's not critical.
