### ISSUE TITLE
Make the Reply box disappear after a comment is posted (but not the top-level Comment box)

### ISSUE THREAD

**Issue by devonandchris** [themotte/rDrama#188]
Leaving it there for me to manually hit "cancel" is literal murder

**Comment by zorbathut** [comment]
So I can explain what happened here :V It used to be that the comment box *would* disappear . . . even the top-level comment box, which was kind of awkward. Then we changed it so the top-level comment box wouldn't disappear . . . but I don't think anyone thought about the *reply* box.

I think the right solution is that the *reply* box should disappear, but the top-level comment box shouldn't. Double-checking, this is actually what Reddit does.

Thankfully I'm pretty sure it'll be a lot easier to make the reply box disappear again than it was to make the top-level comment box not disappear.

Gonna edit your title for a better explanation :)
