### ISSUE TITLE
"Install the The Motte webapp by saving this page to your home screen!""

### ISSUE THREAD

**Issue by orthoxerox** [themotte/rDrama#189]
![Screenshot_20220817-215644](https://user-images.githubusercontent.com/8640149/185220552-62ddc3fa-d6f9-4357-8627-140da2acdbca.png)

I don't know how to get rid of the black banner at the top. Is there even an app?

**Comment by TLSM** [comment]
Tapping should dismiss it. Intended to recommend that a user employs their mobile browser's Pin/Save to Home feature to create a homescreen launcher icon for a website. This is good for reminding people to return, or something.

Recent minor UI improvement on upstream (which also highlights the relevant bits of code) adds an "X" to make it clear tapping works: 
https://github.com/Aevann1/rDrama/commit/5aebc607643aa68bd56726ffb97bf621063920f9
