### ISSUE TITLE
Just find all the Marsey images and remove/replace them.

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#20]
There's a lot. Find them, figure out something sensible to do with them.

Note:

There's something in the game industry that I call "design by default", which is that if you design something, and it's good enough, it might just turn into the actual thing we use. If you think you're good enough at doing the less-codey things, just do it. If you don't, but you're cool with doing the coding work, please do the coding work and insert something blatantly wrong where the actual content is meant to go, then note it here so someone goes through and does the final prep (probably Zorba).

**Comment by mjhouse** [comment]
Do we want to use emojis at all? I'm assuming not. If that assumption is incorrect, let me know. Tentative list of things that need to change for this:

- [x] Replace images in `files/templates/errors` error pages
- [x] Find and remove hardcoded `/e/` paths in templates
- [x] Delete `files/assets/images/emojis/` directory, basically
- [ ] Remove `emoji` endpoint in static.py
- [x] Remove include for `files/assets/js/emoji_modal.js`
- [ ] Remove `render_emoji(...)` from sanitize.py
- [x] Delete emoji-specific handling from lines 197-213 in sanitize.py
- [ ] Delete `filter_emojis_only(...)` from sanitize.py and all usages

**Comment by mjhouse** [comment]
Functions:
* Left `emoji`, `marseys`/`marsey_list` endpoints in static.py
* Left `render_emoji` but commented references
* Left `filter_emojis_only` but commented emoji-specific code inside

Files:

Removed references and-

 * Deleted `files/assets/js/emoji_modal.js`
 * Deleted `files/templates/emoji_modal.html`
 * Deleted `files/templates/marseys.html`

**Comment by mjhouse** [comment]
Resolved by #88 and #89
