### ISSUE TITLE
Comment count appears invalid

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#206]
See https://www.dev.themotte.org/post/112/shall-we-test-really-long-reply

This is higher-priority than it seems because I use comment count as a rough barometer of how much traffic the community is getting.

**Comment by TLSM** [comment]
There's special case logic for comment replies-to-self (`rts`) not counting toward parent post's comment count. I am frankly unsure of why this is.

https://github.com/themotte/rDrama/blob/6b53867ae13176bfea684cfd6f28cc655358101a/files/routes/comments.py#L173-L182
https://github.com/themotte/rDrama/blob/6b53867ae13176bfea684cfd6f28cc655358101a/files/routes/comments.py#L397-L399

**Comment by zorbathut** [comment]
Weird.

Well, won't be hard to fix, then. If nobody scoops me on it I'll try to get it done soon.
