### ISSUE TITLE
Modlog (/log, /modlog) 500'ing on prod

### ISSUE THREAD

**Issue by TLSM** [themotte/rDrama#216]
https://www.dev.themotte.org/log yields a user-visible 500 error as of 2022-08-27 07:20 UTC.

It works in my local instance, so this seems data-dependent for something on prod. Stack trace would probably solve it @zorbathut

**Comment by zorbathut** [comment]
![image](https://user-images.githubusercontent.com/160754/187027791-5d567101-0efb-45d9-be0e-6ff69ee19362.png)

I'm betting the filter-post stuff isn't entirely set up right.

**Comment by zorbathut** [comment]
I see what's going on here - if you're not already on it, I'll handle it :) (let me know if you are)
