### ISSUE TITLE
Users may be unable to send messages while banned?

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#221]
I got this report but I can't find the error because the log is full of spam. This may or may not be legit; if it is, though, it's pretty important.

**Comment by TLSM** [comment]
routes/users.py:`message2(⋅)` is wrapped with `@is_not_permabanned`, which checks:

https://github.com/themotte/rDrama/blob/de4d923b32fda1ee39ace9ab1977321b36d986e5/files/helpers/wrappers.py#L94-L95

This shouldn't affect temp-banned users (confirmed also in local testing). Also, both temp- and perma-banned users can still use modmail.

**Comment by zorbathut** [comment]
I think a reasonable fix here, then, would be to keep an error in, but change it into "you have been permabanned and cannot send messages; contact modmail (with link) if you think this decision was incorrect".
