### ISSUE TITLE
Comments removed in threads does not decrement the thread comment count

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#231]

**Comment by justcool393** [comment]
this seems to be fixed

![image](https://github.com/themotte/rDrama/assets/1238820/c6c0ded9-139b-4376-91c3-2faf4fdd3ae7)

![image](https://github.com/themotte/rDrama/assets/1238820/46b30fd1-ab48-4f66-81d8-61ea1e0b43dd)
