### ISSUE TITLE
De-float header

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#234]
See https://www.reddit.com/r/TheMotte/comments/x5t3jh/meta_the_motte_is_dead_long_live_the_motte/in35ac1/

**Comment by dmlerner** [comment]
I believe the simplest fix would be to remove "fixed-top" from header.html line 2. I'm not a frontend dev, so I don't know if that will leave it at the top with absolute position, or if we need to manually add something to that effect. 

I'd also support removing the entire fixed-top class from main.css, and changing all references to absolute-top (which doesn't currently exist).
