### ISSUE TITLE
Removed posts should be grayed out for admins so they're easier (possible) to recognize as removed.

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#237]

**Comment by mjhouse** [comment]
@zorbathut Is this different from when a user deletes their own post? Because on my local fork, those posts are greyed out for an admin.

**Comment by zorbathut** [comment]
I think this might be "Removed through the filter system", although we also *really* need to reconcile that with the original removal; it's weird that we have two different kinds of removal.

Y'know what, let me just make a new task for this specifically: https://github.com/themotte/rDrama/issues/359

I *think* that will actually fix this. But it's also a bit of a bigger task, now that I know the task is actually bigger.

**Comment by DinoInNameOnly** [comment]
I was gonna work on this but I don't understand the scope, If admin removes a post it looks like this to admin. Is this task done already? Or was something else meant by the task.

![Screen Shot 2022-11-04 at 3 54 20 PM](https://user-images.githubusercontent.com/112996131/200086284-5317d96d-35c5-4da3-81e6-69d64f718dc9.png)

**Comment by zorbathut** [comment]
I think I'm honestly killing this just because #359 is the real issue; we have too many ways to remove stuff and I think they may work differently. Gotta reconcile those!
