### ISSUE TITLE
Fix corner image size.

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#240]
"Also, tangentially the corner "motte" logo is almost a megabyte in size even so; you probably scale it down significantly. Edit: It's used as the favicon too, albeit with a different name (and wrong type, it shouldn't be "image/png"), so it's downloaded twice."

**Comment by DinoInNameOnly** [comment]
@zorbathut It looks like you fixed this? https://github.com/themotte/rDrama/pull/323 and https://github.com/themotte/rDrama/pull/313

**Comment by zorbathut** [comment]
Oops, totally did. Good catch, thanks!
