### ISSUE TITLE
Remove highlighting for highly-downvoted comments.

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#245]

**Comment by TLSM** [comment]
This is the orange/reddish highlighting you mean? Like [as seen here](https://www.themotte.org/post/6/greetings-mottizens/276?context=8#context):
![image](https://user-images.githubusercontent.com/104547575/188351106-560ff379-f10a-4c5e-b1dc-2af8ada691e5.png)

This is highlighting for controversial comments and, strictly speaking, it appears when `downvotes > 5 and 0.25 < upvotes / downvotes < 4`. Would you prefer totally gutting the logic that applies the `.controversial` class, or just removing the styling from `.controversial`? Reddit displayed a dagger † on controversial comments, which I think was the original inspiration for the coloring. One part design question (should controversial comments be shown as such in any way?), one part software question (do we just hide the styling, or remove the logic altogether?)

**Comment by zorbathut** [comment]
Hmm.

Let's go with "hide the styling" for now, then; that seems easiest and also leaves the infrastructure in place for more things.
