### ISSUE TITLE
Add canned options to the Report field.

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#26]
Right now the Report field is just a plaintext field. Add a radio button set so people can default to one of our rules. Leave the plaintext in if they want to write more or want to write something custom, though.

**Comment by JulianRota** [comment]
Do we have a list of specific reasons we'd like radio buttons for? I'm thinking basically taking things from the rules adjusted into a form short enough for the report page

**Comment by zorbathut** [comment]
Yeah, those plus "Actually A Quality Contribution".

Honestly, the hard part is just putting together the code; even if you just submitted a changelist with "Reason A", "Reason B", "Fill These In Yourself Zorba Dammit", I'd give it a thumbs-up.
