### ISSUE TITLE
Fix the popup profile card

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#297]
See https://www.themotte.org/post/30/bugs-suggestions-small-comments-and-site/3826?context=8#context - can this be easily fixed?

**Comment by DinoInNameOnly** [comment]
@zorbathut The way it works on rDrama is that you click on a username and it shows the usercard and if you click "view" in the bottom right you can actually go to their profile. To restore this behavior, we just have to undo https://github.com/themotte/rDrama/commit/8f973ff9c9d9e420e084741bcbbd32072b51ecaf

If we want the mouseover behavior suggested by KulakRevolt that would take a little more work.

**Comment by TLSM** [comment]
For reference, we fixed this same problem on the upstream not long after TheMotte forked. The JS might be reusable?
https://github.com/TLSM/rDrama/commit/fa347a40c6580bc9bda5416f6a6d8e9a00bef6b3
