### ISSUE TITLE
Something is broken with filtered comments while logged out

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#298]
I've seen this a few times - people seem to be able to see filtered comments while logged out but not while logged in. I haven't managed to reproduce it but it's been mentioned enough times that something might be busted here.

**Comment by zorbathut** [comment]
See https://www.themotte.org/post/30/bugs-suggestions-small-comments-and-site/3604?context=8#context - I'll collect more reports here as I go.

**Comment by zorbathut** [comment]
https://www.themotte.org/post/30/bugs-suggestions-small-comments-and-site/4004?context=8#context

**Comment by mjhouse** [comment]
What do you mean by "filtered"? I'm trying to reproduce this or figure out what's going on with it.

**Comment by zorbathut** [comment]
Go into the Site Settings and turn up the Comment Filtering options. Make a new non-admin account and use that to post some comments. Your admin account should see "approve" and "reject" buttons on those posts. Now log out entirely; I *think* the comment will be visible, when it shouldn't be visible at all.

(If you create *another* non-admin account, you shouldn't see those posts.)

It's sort of a temporary per-comment shadowban behavior, until we hit the "approve" button.
