### ISSUE TITLE
Review rules for reddit references

### ISSUE THREAD

**Issue by mjhouse** [themotte/rDrama#31]
There are probably references to reddit or reddit mechanisms that no longer make sense in the new site. These should be removed or updated. This issue relies on #30.

**To update the sidebar/rules, modify the following files**:

* files/templates/sidebar_TheMotte.html
* files/templates/rules.html

**Comment by mjhouse** [comment]
Waiting on #12 as well

**Comment by zorbathut** [comment]
Fair 'nuff, this is my problem, I'll handle it :)
