### ISSUE TITLE
Can't report comments

### ISSUE THREAD

**Issue by DinoInNameOnly** [themotte/rDrama#360]
Many people have reported this. Probably related to the recent change to add the categories to the report button.

1. https://www.themotte.org/post/86/culture-war-roundup-for-the-week/11008?context=8#context <-- has a hypothesis about the problem
2. https://www.themotte.org/post/86/culture-war-roundup-for-the-week/10911?context=8#context
3. https://www.themotte.org/post/76/meta-out-of-the-frying-pan/10927?context=8#context

@JulianRota and @zorbathut for visibility

**Comment by zorbathut** [comment]
Whoops. Thanks for letting me know! Fixed in #361 .

**Comment by JulianRota** [comment]
Yeah sorry, my mistake
