### ISSUE TITLE
Replying to a Load-More deep thread results in an internal error

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#364]

**Comment by JulianRota** [comment]
I tried this a bunch of times with the latest code checked out and it worked fine every time. Is anyone else able to reproduce? Anything more specific on under what conditions this happens?

**Comment by zorbathut** [comment]
Well, now I can't reproduce this.

Unfortunately the last time it happened I was just running out the door and couldn't poke at it; next time it happens I'll see if I can get more info, I've actually had it happen a few times now.

**Comment by zorbathut** [comment]
(I doubt this has been fixed, but if someone's reading this a month from now and I haven't updated it, I guess it's been fixed, pester me to close it, thanks)

**Comment by zorbathut** [comment]
Welp, I haven't seen it since. I have no idea what happened to it. Closing this, I suppose!
