### ISSUE TITLE
Thoroughly fix problems with sorted nested comments

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#370]
We seem to be having recurring issues with nested comment sorting. From PM:

"I'm viewing it logged-out, and when I try and sort a subthread by "Top", the site still shows it to me sorted by "New". Tested eg here: https://www.themotte.org/post/86/culture-war-roundup-for-the-week/11990?sort=top#context"

From public:

https://www.themotte.org/post/76/meta-out-of-the-frying-pan/13165?context=8#context

My gut feeling is that we need to go do something more thorough to fix this once and for all, but I'm not sure what exact form this takes.

**Comment by justcool393** [comment]
fixed in #439 and #490
