### ISSUE TITLE
User appears to be logged out when visiting some pages

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#384]
"Bug: looking at certain pages like ":user/following" and "admins" seems to log you out (you get logged back in when leaving to non-broken pages)/"

I think I know what's going on here; https://github.com/themotte/rDrama/pull/374 removed the auth requirement entirely, and it should have changed to an authorization-optional tag (we already have one, I just forget what it's called.) Shouldn't be hard to fix; we should probably also browse our entrypoints and make sure that tag exists on *most* pages.

**Comment by electricwhisk** [comment]
This error applies to the `/contact` page as well.
