### ISSUE TITLE
Implement Alembic for database updates.

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#39]
We already accidentally missed one schema change and we've been working on this for two days, we should fix this.

Alembic appears to be the right solution. Someone should set this up so it works.

Also, this should be rigged up to Github Actions, so that if you try a pull request without (if necessary) updating the Alembic data, it yells at you and refuses to work. You'll want to test this in a fork so you can just provide the .github folder.

**Comment by zorbathut** [comment]
(then zorba gets to figure out how to wire this into kubernetes, but that's zorba's problem)

**Comment by faul-sname** [comment]
Taking a shot at this

**Comment by zorbathut** [comment]
Calling this one done!
