### ISSUE TITLE
Submitting Contact form results in 405

### ISSUE THREAD

**Issue by electricwhisk** [themotte/rDrama#391]
Submitting the `Contact` form results in a GET request that returns a `Method Not Allowed`.

Steps to reproduce:
1. Sign in
2. Navigate to Contact page (observe that you appear to be logged out now, as mentioned in #384)
3. Fill out message box and submit.
4. Observe that it made a GET request with the form fields as query parameters, which returns a 405.

**Comment by electricwhisk** [comment]
It looks like what is happening here is that due to the auth issue in https://github.com/themotte/rDrama/issues/384, submitting the form makes a POST to `/send_admin`, which results in a `302 FOUND` with a `Location` header that points to the `/login` endpoint with a parameter to redirect back to `/send_admin`. This redirection from the login page is what creates the 405, but it's a symptom of the auth issue.

**Comment by zorbathut** [comment]
I *think* this may have been fixed now, but can someone who isn't me try it out?

**Comment by electricwhisk** [comment]
Can confirm that it is resolved.
