### ISSUE TITLE
Markdown implementation fails to produce hard line breaks properly

### ISSUE THREAD

**Issue by ToaKraka** [themotte/rDrama#440]
According to the CommonMark specification ([1](https://spec.commonmark.org/0.30/#hard-line-breaks) [2](https://spec.commonmark.org/0.30/#raw-html)), it should be possible for a user to create [a `br` (line-break) element](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-br-element) in the HTML output by typing one of the following character sequences at the end of a line:

- `  ` (two spaces);
- `\` (a reverse slash); or
- `<br/>`.

However, it [appears](https://www.themotte.org/post/204/smallscale-question-sunday-for-november-27/36944?context=8#context) that none of those methods is functioning at the moment.

**Comment by zorbathut** [comment]
Yep, that's not ideal. Gonna just link this to #266 - in general we have a bunch of work to do on the markdown renderer.

**Comment by justcool393** [comment]
> [#266 (comment)](https://github.com/themotte/rDrama/issues/266#issuecomment-1288108270)
> 
> re linebreaks: @zorbathut this is WAI from rDrama's perspective but probably not from themotte's. there was some specific code added to sanitize.py to make single line breaks into paragraph breaks
> 
> https://www.themotte.org/post/216/meta-something-shiny-and-two-things/57849?context=8#context
> 
> the subject of the great holy \n war (i.e. me and @official-techsupport and @TLSM discussing it a bit and getting confused on over what each other was saying)

for those coming in and haven't looked at #266 yet, this was my comment over there.
personally don't have an opinion either way, but rdrama's non-conformance was intentional
