### ISSUE TITLE
Making a post fails with an error regarding a 'new' keyword

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#49]
![image](https://user-images.githubusercontent.com/160754/167411735-c94672d5-ae4c-49a0-a5a5-59cb0ea56b9b.png)

This is probably related to https://github.com/themotte/rDrama/commit/19d54d8521c4338c4f487877f7291177fa5fed9c or https://discord.com/channels/722487636488486913/722487636488486916/973201058551713792 by @64617 ; leaving it up for anyone who grabs it, though.

**Comment by JamPaladin** [comment]
I *THINK* I fixed it, at least seems to work on my local instance. Unsure why my first PR changed files I didn't change - git remains a learning experience.

**Comment by iro84657** [comment]
Whoops, this was my fault. I tested it when I first made the change; this will teach me to always test again after rebasing.
