### ISSUE TITLE
Posting comments in deeply nested threads hangs

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#594]
From cjet79:

When posting a comment in a deeply nested thread. (deep enough that any subsequent comments will be minimized. I think 9 comments deep.) When clicking "comment" the page will hang. 

There is also a javascript error that gets thrown in the console:
Uncaught TypeError: comments is null
    onload https://www.themotte.org/assets/js/comments_v.js?v=a90eb7d7:293
    post_comment https://www.themotte.org/assets/js/comments_v.js?v=a90eb7d7:280
    onclick https://www.themotte.org/post/508/culture-war-roundup-for-the-week/103865?context=8#context:1
comments_v.js:293:4
    onload https://www.themotte.org/assets/js/comments_v.js?v=a90eb7d7:293
    (Async: EventHandlerNonNull)
    post_comment https://www.themotte.org/assets/js/comments_v.js?v=a90eb7d7:280
    onclick https://www.themotte.org/post/508/culture-war-roundup-for-the-week/103865?context=8#context:1

refreshing the page will show that the comment was successfully posted

My best guess is that is an async error, and the page is trying to load the "more comments" button before the comment has been fully saved and retrieved from the server

![image](https://github.com/themotte/rDrama/assets/160754/c0f32262-d7e3-4057-bb18-c5c042dd9096)

**Comment by justcool393** [comment]
can reproduce, might be related to `?context`???

![image](https://github.com/themotte/rDrama/assets/1238820/685c7d9e-2a64-4063-9b73-0c21bb31cee9)

![image](https://github.com/themotte/rDrama/assets/1238820/308d71f5-0c88-47e8-aba1-a12faf7f2356)

it's worth noting the comment does actually get posted, it just doesn't get inserted into the tree.

![image](https://github.com/themotte/rDrama/assets/1238820/89d4ff81-3035-4443-8bee-b3665353f4ac)

it looks like there simply isn't a `replies-of-<id>` div anywhere in there.

compare a different leaf which does have the div, even if empty

![image](https://github.com/themotte/rDrama/assets/1238820/084a662d-8dfb-4320-9006-9e21a0b1e4a8)

**Comment by zorbathut** [comment]
[Seems to still be happening](https://www.themotte.org/post/611/meta-a-whole-host-of-completed/133614?context=8#context).

**Comment by gldrk** [comment]
There are two code paths involved here.  This PR only changed the rendering for shoah’d comments (where it ironically doesn’t matter).  Needless to say, someone should rewrite that template so that there aren’t two largely identical paths.

**Comment by zorbathut** [comment]
Aha! That makes sense. Many thanks for doing the legwork on this, I'll get it live soon :)

**Comment by zorbathut** [comment]
Should now be live!
