### ISSUE TITLE
UI bug where both approval and removal buttons are visible

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#600]
From https://github.com/themotte/rDrama/pull/596:

> There's a UI bug where both approval and removal buttons are visible at once, even on the happy path. Fix: s/d-md-inline-block/d-md-block/g on files/assets/js/comments_admin.js. Think the template changed at some point which wasn't reflected in JS (and pre-dates this change).

**Comment by justcool393** [comment]
was this fixed by #637? since we're not replacing button inner html anymore (just hiding (unhiding) the same (opposite) buttons), this should be fixed

**Comment by zorbathut** [comment]
Probably, yeah. I'll close it.
