### ISSUE TITLE
Private Profile revamp

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#651]
Private profiles are going to be restricted to users "in good standing", or people who have requested it from the mods. We're leaving the functionality in, just really cutting back on who can access it.

* Add a "Private Profile Toggle Allowed" function that tests the user's account age, total karma, and comment count against thresholds. (This is similar to the Filtering test, but with different numbers; feel free to just duplicate the code with new constants.)
* If Private Profile Toggle isn't allowed for a user, gray out the slider and add a note saying that you can message the mods if you have good reason to have a private profile.
* (Make sure this is enforced on the server as well.)
* Add a Private Profile Toggle switch on user profiles that's visible to (and usable by) only mods.

**Comment by justcool393** [comment]
What JL do we want this to be: 1, 2, or 3?

**Comment by zorbathut** [comment]
Janitor level, I'm assuming? Uh, hrm. I guess the same one that lets mods ban people, that seems reasonable.

**Comment by justcool393** [comment]
oh yeah i guess the official nomenclature is admin level :P  
sounds good
