### ISSUE TITLE
Fix user popup.

### ISSUE THREAD

**Issue by zorbathut** [themotte/rDrama#78]
On rdrama.net you can click people's usernames to get a nice little popup, like so:

![image](https://user-images.githubusercontent.com/160754/168490516-2daf747a-0cd5-4fcf-8e7a-66877f486432.png)

For some reason this doesn't work on our site. Why not? I dunno.

We do have an on-click href now, which allows you to middle-click to open-in-new-tab, but it'd be nice if the popup overrode it if JS is enabled.

**Comment by DinoInNameOnly** [comment]
This was fixed by https://github.com/themotte/rDrama/pull/367

**Comment by zorbathut** [comment]
So it was! Thanks for the notification :)
